# Generated by Django 4.2.4 on 2023-08-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="blarg",
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
