# Generated by Django 4.2.4 on 2023-08-12 21:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0002_remove_book_blarg_alter_book_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        "\\d{10}", message="ISBN are 10 numeric characters"
                    )
                ],
            ),
        ),
    ]
