# Generated by Django 4.2.4 on 2023-08-12 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0003_alter_book_isbn"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="publicationDate",
            field=models.DateField(default=datetime.date(2023, 8, 12)),
        ),
    ]
