# Generated by Django 4.2.4 on 2023-08-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0004_book_publicationdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.TextField(default="", max_length=1000),
        ),
    ]
