# Generated by Django 4.2.4 on 2023-08-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0006_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(to="collection.author"),
        ),
    ]
