# Generated by Django 4.2.4 on 2023-08-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0009_author_books"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="books",
            field=models.ManyToManyField(blank=True, null=True, to="collection.book"),
        ),
    ]
