# Generated by Django 4.2.4 on 2023-08-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0010_alter_author_books"),
    ]

    operations = [
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="author",
            name="bio",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="author",
            name="primaryGenre",
            field=models.CharField(default="", max_length=100),
        ),
    ]
