# Generated by Django 4.2.4 on 2023-08-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0011_series_author_bio_author_primarygenre"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="primaryGenre",
            new_name="primary_genre",
        ),
        migrations.RenameField(
            model_name="book",
            old_name="publicationDate",
            new_name="publication_date",
        ),
        migrations.AddField(
            model_name="series",
            name="primary_genre",
            field=models.CharField(default="", max_length=100),
        ),
    ]
