# Generated by Django 4.2.4 on 2023-08-13 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0012_rename_primarygenre_author_primary_genre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="number_in_series",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="book",
            name="series",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="collection.series",
            ),
        ),
    ]
