# Generated by Django 4.2.4 on 2023-08-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0018_remove_author_books"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(related_name="books", to="collection.author"),
        ),
    ]
