# Generated by Django 4.2.4 on 2023-08-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0019_alter_book_authors"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="tags",
            field=models.ManyToManyField(related_name="books", to="collection.tag"),
        ),
    ]
