# Generated by Django 4.2.4 on 2023-08-14 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0020_tag_book_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="series",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="collection.series",
            ),
        ),
    ]
