# Generated by Django 4.2.4 on 2023-08-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0021_alter_book_series"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                null=True,
                related_name="books",
                to="collection.tag",
            ),
        ),
    ]
